/**
 * Tenant Layout Route — /_app/$slug
 *
 * Entry point for all per-tenant BOOST! screens.
 * - Resolves tenant by slug + caller's role via getMyTenantContext()
 * - Redirects to /auth if not logged in (inherited from _app parent)
 * - Redirects to /dashboard if caller has no access to this tenant
 * - Injects TenantContext for all child routes
 *
 * DO NOT touch: routeTree.gen.ts (auto-generated by TanStack Router)
 * This file must be named $slug.tsx — TanStack dot-separated routing.
 */
import { createFileRoute, Outlet, redirect } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useSuspenseQuery, queryOptions } from "@tanstack/react-query";
import { getMyTenantContext } from "@/lib/tenant-auth.functions";
import type { TenantContext } from "@/lib/tenant-auth.functions";
import { TenantProvider } from "@/contexts/tenant-context";
import type { TenantCtxValue, TenantRole } from "@/contexts/tenant-context";

// ---------------------------------------------------------------------------
// Route definition
// ---------------------------------------------------------------------------
export const Route = createFileRoute("/_app/$slug")({
  // Server-side loader: resolves tenant context, throws early if forbidden
  loader: async ({ params, context }) => {
    try {
      // getMyTenantContext is called via the queryClient on the server
      // We throw redirect instead of returning null so the user never
      // sees a flash of the tenant shell for a tenant they can't access.
      const tenantCtx: TenantContext = await (context as any).queryClient
        .fetchQuery(
          tenantContextQuery(params.slug, () =>
            fetch(`/api/tenant-context?slug=${encodeURIComponent(params.slug)}`).then(
              (r) => r.json(),
            ),
          ),
        )
        .catch(() => null);
      if (!tenantCtx) throw redirect({ to: "/dashboard", replace: true });
      return tenantCtx;
    } catch (err: any) {
      if (err?.message === "Forbidden" || err?.message === "NotFound") {
        throw redirect({ to: "/dashboard", replace: true });
      }
      throw err;
    }
  },
  component: TenantLayout,
  errorComponent: TenantError,
});

// ---------------------------------------------------------------------------
// Query factory
// ---------------------------------------------------------------------------
function tenantContextQuery(
  slug: string,
  fetcher: () => Promise<TenantContext>,
) {
  return queryOptions({
    queryKey: ["tenant-context", slug],
    queryFn: fetcher,
    staleTime: 5 * 60 * 1000, // 5 min — roles don't change mid-session
    retry: false,
  });
}

// ---------------------------------------------------------------------------
// Layout component
// ---------------------------------------------------------------------------
function TenantLayout() {
  const { slug } = Route.useParams();
  const fn = useServerFn(getMyTenantContext);

  const { data: tenantCtx } = useSuspenseQuery(
    tenantContextQuery(slug, () => fn({ data: { slug } })),
  );

  if (!tenantCtx) return null;

  const role = tenantCtx.callerRole as TenantRole;

  const ctxValue: TenantCtxValue = {
    tenant: tenantCtx.tenant,
    callerRole: role,
    isSuperAdmin: role === "super_admin",
    isBsgAdmin: role === "bsg_admin",
    isTenantAdmin: role === "tenant_admin",
    isManager: role === "manager",
    isLearner: role === "learner" || role === "instructor" || role === "mentor",
    canAdminTenant:
      role === "super_admin" ||
      role === "bsg_admin" ||
      role === "tenant_admin",
  };

  return (
    <TenantProvider value={ctxValue}>
      <Outlet />
    </TenantProvider>
  );
}

// ---------------------------------------------------------------------------
// Error boundary
// ---------------------------------------------------------------------------
function TenantError({ error }: { error: Error }) {
  if (
    error.message.includes("Forbidden") ||
    error.message.includes("NotFound")
  ) {
    // Redirect client-side if server redirect didn't fire
    if (typeof window !== "undefined") {
      window.location.replace("/dashboard");
    }
    return null;
  }
  return (
    <div className="grid min-h-screen place-items-center p-6 text-sm text-muted-foreground">
      Could not load tenant workspace: {error.message}
    </div>
  );
}
