import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect } from "react";
import { useAuth } from "@/hooks/use-auth";
import { Button } from "@/components/ui/button";
import {
  Activity,
  Award,
  BookOpen,
  Briefcase,
  Building2,
  GraduationCap,
  ShieldCheck,
  Sparkles,
  Target,
} from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "BOOST Learning & Credentialing Platform" },
      {
        name: "description",
        content:
          "AI-powered learning, certification, and apprenticeship platform. Four modules — Roles, Perform, Pulse, Learn — for workforce, corporate, and apprenticeship programs.",
      },
      { property: "og:title", content: "BOOST Learning & Credentialing Platform" },
      {
        property: "og:description",
        content:
          "Build, deliver, and credential learning experiences with AI assistance — Roles, Perform, Pulse, Learn.",
      },
      { property: "og:url", content: "/" },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
    links: [{ rel: "canonical", href: "/" }],
  }),
  component: Landing,
});

const MODULES = [
  {
    icon: Briefcase,
    name: "Boost!Roles",
    tag: "Org clarity",
    body: "Org charts, job descriptions, and role libraries — generated by AI, owned by you.",
  },
  {
    icon: Target,
    name: "Boost!Perform",
    tag: "Performance",
    body: "Goal programs, performance plans, and review cycles with email-verified publishing.",
  },
  {
    icon: Activity,
    name: "Boost!Pulse",
    tag: "Engagement",
    body: "Employee surveys and pulse cadences with confirmation before any survey goes live.",
  },
  {
    icon: BookOpen,
    name: "Boost!Learn",
    tag: "Learning",
    body: "Course catalog, apprenticeship RTI, CEUs, and stackable credentials in one place.",
  },
];

const VERTICALS = [
  "Workforce development boards",
  "Behavioral health & social work",
  "Skilled trades apprenticeship",
  "Corporate academies",
  "Faith-based & community programs",
  "Industry associations",
];

function Landing() {
  const { user, loading } = useAuth();
  const navigate = useNavigate();
  useEffect(() => {
    if (!loading && user) navigate({ to: "/dashboard" });
  }, [loading, user, navigate]);

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5">
          <div className="flex items-center gap-2">
            <div className="grid h-9 w-9 place-items-center rounded-md bg-primary text-primary-foreground font-display font-semibold">
              B
            </div>
            <div className="leading-tight">
              <div className="font-display text-lg font-semibold">BOOST</div>
              <div className="text-xs text-muted-foreground">Learning & Credentialing Platform</div>
            </div>
          </div>
          <Link to="/auth">
            <Button variant="ghost">Sign in</Button>
          </Link>
        </div>
      </header>

      <main>
        <section className="mx-auto max-w-6xl px-6 py-20">
          <p className="mb-4 inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-1 text-xs font-medium text-muted-foreground">
            <Sparkles className="h-3 w-3 text-accent" /> AI-powered. IACET-aligned. Built by Boost Strategy Group.
          </p>
          <h1 className="font-display text-5xl font-semibold leading-[1.05] tracking-tight md:text-6xl">
            Four modules. One platform.
            <br />
            <span className="text-accent">A workforce that performs.</span>
          </h1>
          <p className="mt-6 max-w-2xl text-lg text-muted-foreground">
            Boost!Roles, Boost!Perform, Boost!Pulse, and Boost!Learn — a unified system for role
            design, performance, engagement, and credentialed learning. Self-paced, hybrid, and
            live-instructor-led, all in your brand.
          </p>
          <div className="mt-8 flex flex-wrap gap-3">
            <Link to="/auth">
              <Button size="lg" className="bg-primary text-primary-foreground">Get started</Button>
            </Link>
            <a href="#modules">
              <Button size="lg" variant="outline">Tour the modules</Button>
            </a>
          </div>
        </section>

        <section id="modules" className="border-t border-border bg-card">
          <div className="mx-auto max-w-6xl px-6 py-16">
            <h2 className="font-display text-3xl font-semibold">The four modules</h2>
            <p className="mt-2 max-w-2xl text-sm text-muted-foreground">
              Use one. Use all four. They share the same employee directory, the same approvals,
              and the same audit trail.
            </p>
            <div className="mt-8 grid gap-6 md:grid-cols-2 lg:grid-cols-4">
              {MODULES.map(({ icon: Icon, name, tag, body }) => (
                <div key={name} className="rounded-xl border border-border bg-background p-6">
                  <Icon className="h-6 w-6 text-accent" />
                  <div className="mt-4 text-xs font-medium uppercase tracking-wide text-muted-foreground">
                    {tag}
                  </div>
                  <h3 className="mt-1 font-display text-xl font-semibold">{name}</h3>
                  <p className="mt-2 text-sm text-muted-foreground">{body}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="mx-auto max-w-6xl px-6 py-16">
          <h2 className="font-display text-3xl font-semibold">Built for the way you operate</h2>
          <div className="mt-8 grid gap-6 md:grid-cols-3">
            {[
              { icon: Sparkles, title: "BOOST! Implementation Agent", body: "An animated AI agent walks each module through setup, drafts artifacts, and routes anything beyond config to support." },
              { icon: ShieldCheck, title: "Approval-gated publishing", body: "Performance plans, goal programs, and surveys require an email-confirmed approval before going live. Every approver and timestamp is logged." },
              { icon: Building2, title: "Multi-tenant & white-label", body: "Stand up a branded portal for every program, partner, or academy. Per-tenant entitlements, branding, and domain." },
              { icon: Award, title: "Stackable credentials", body: "CEUs, course certificates, and stackable credentials with verifiable badges." },
              { icon: GraduationCap, title: "Apprenticeship & RTI", body: "Per-learner RTI dashboards, mentor view, and GoSprout-compatible CSV exports." },
              { icon: Briefcase, title: "Funding-source aware", body: "Self-pay, grant, ETPL, RTI, workforce board, corporate sponsor — tagged end-to-end." },
            ].map(({ icon: Icon, title, body }) => (
              <div key={title} className="rounded-xl border border-border bg-background p-6">
                <Icon className="h-6 w-6 text-accent" />
                <h3 className="mt-4 font-display text-lg font-semibold">{title}</h3>
                <p className="mt-2 text-sm text-muted-foreground">{body}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="border-t border-border bg-card">
          <div className="mx-auto max-w-6xl px-6 py-16">
            <h2 className="font-display text-3xl font-semibold">Who we serve</h2>
            <p className="mt-2 max-w-2xl text-sm text-muted-foreground">
              Programs across these verticals run on BOOST today.
            </p>
            <ul className="mt-6 grid gap-3 md:grid-cols-2 lg:grid-cols-3">
              {VERTICALS.map((v) => (
                <li
                  key={v}
                  className="rounded-lg border border-border bg-background px-4 py-3 text-sm"
                >
                  {v}
                </li>
              ))}
            </ul>
          </div>
        </section>

        <section className="mx-auto max-w-6xl px-6 py-20 text-center">
          <h2 className="font-display text-3xl font-semibold">Ready to see BOOST in your brand?</h2>
          <p className="mt-3 text-muted-foreground">Sign in or request a tenant to get started.</p>
          <div className="mt-6">
            <Link to="/auth">
              <Button size="lg" className="bg-primary text-primary-foreground">Get started</Button>
            </Link>
          </div>
        </section>
      </main>

      <footer className="border-t border-border">
        <div className="mx-auto max-w-6xl px-6 py-8 text-sm text-muted-foreground">
          © {new Date().getFullYear()} Boost Strategy Group. IACET accredited provider. ASWB® is a
          registered trademark of the Association of Social Work Boards.
        </div>
      </footer>
    </div>
  );
}

