import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect } from "react";
import { useAuth } from "@/hooks/use-auth";
import { Button } from "@/components/ui/button";
import {
  Activity,
  ArrowRight,
  Award,
  BookOpen,
  Briefcase,
  Building2,
  CheckCircle2,
  GraduationCap,
  ShieldCheck,
  Sparkles,
  Target,
} from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "BOOST Learning & Credentialing Platform" },
      {
        name: "description",
        content:
          "AI-powered learning, certification, and apprenticeship platform. Four modules — Roles, Perform, Pulse, Learn — for workforce, corporate, and apprenticeship programs.",
      },
      { property: "og:title", content: "BOOST Learning & Credentialing Platform" },
      {
        property: "og:description",
        content:
          "Build, deliver, and credential learning experiences with AI assistance — Roles, Perform, Pulse, Learn.",
      },
      { property: "og:url", content: "/" },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
    links: [{ rel: "canonical", href: "/" }],
  }),
  component: Landing,
});

const MODULES = [
  {
    icon: Briefcase,
    name: "Boost!Roles",
    tag: "Org clarity",
    body: "Org charts, job descriptions, and role libraries — generated by AI, owned by you.",
    points: ["AI-drafted job descriptions", "Reusable role libraries", "Live org charts"],
  },
  {
    icon: Target,
    name: "Boost!Perform",
    tag: "Performance",
    body: "Goal programs, performance plans, and review cycles with email-verified publishing.",
    points: ["Goal & review cycles", "Approval-gated publishing", "Audit-logged sign-off"],
  },
  {
    icon: Activity,
    name: "Boost!Pulse",
    tag: "Engagement",
    body: "Employee surveys and pulse cadences with confirmation before any survey goes live.",
    points: ["Pulse & engagement surveys", "Confirmation before launch", "Trend reporting"],
  },
  {
    icon: BookOpen,
    name: "Boost!Learn",
    tag: "Learning",
    body: "Course catalog, apprenticeship RTI, CEUs, and stackable credentials in one place.",
    points: ["Course catalog & CEUs", "Apprenticeship RTI", "Stackable credentials"],
  },
];

const CAPABILITIES = [
  {
    icon: Sparkles,
    title: "BOOST! Implementation Agent",
    body: "An animated AI agent walks each module through setup, drafts artifacts, and routes anything beyond config to support.",
  },
  {
    icon: ShieldCheck,
    title: "Approval-gated publishing",
    body: "Performance plans, goal programs, and surveys require an email-confirmed approval before going live. Every approver and timestamp is logged.",
  },
  {
    icon: Building2,
    title: "Multi-tenant & white-label",
    body: "Stand up a branded portal for every program, partner, or academy. Per-tenant entitlements, branding, and domain.",
  },
  {
    icon: Award,
    title: "Stackable credentials",
    body: "CEUs, course certificates, and stackable credentials with verifiable badges.",
  },
  {
    icon: GraduationCap,
    title: "Apprenticeship & RTI",
    body: "Per-learner RTI dashboards, mentor view, and GoSprout-compatible CSV exports.",
  },
  {
    icon: Briefcase,
    title: "Funding-source aware",
    body: "Self-pay, grant, ETPL, RTI, workforce board, corporate sponsor — tagged end-to-end.",
  },
];

const VERTICALS = [
  "Workforce development boards",
  "Behavioral health & social work",
  "Skilled trades apprenticeship",
  "Corporate academies",
  "Faith-based & community programs",
  "Industry associations",
];

const STEPS = [
  {
    step: "01",
    title: "Stand up your tenant",
    body: "Branded portal, domain, and entitlements configured with the Implementation Agent.",
  },
  {
    step: "02",
    title: "Build with AI",
    body: "Draft roles, plans, surveys, and courses — then review and approve before anything publishes.",
  },
  {
    step: "03",
    title: "Deliver & credential",
    body: "Run self-paced, hybrid, or instructor-led programs and issue verifiable credentials.",
  },
];

function Landing() {
  const { user, loading } = useAuth();
  const navigate = useNavigate();
  useEffect(() => {
    if (!loading && user) navigate({ to: "/dashboard" });
  }, [loading, user, navigate]);

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-40 border-b border-border bg-background/80 backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-2.5">
            <div className="grid h-9 w-9 place-items-center rounded-md bg-primary font-display font-semibold text-primary-foreground">
              B
            </div>
            <div className="leading-tight">
              <div className="font-display text-lg font-semibold">BOOST</div>
              <div className="text-xs text-muted-foreground">Learning &amp; Credentialing Platform</div>
            </div>
          </div>
          <nav className="hidden items-center gap-6 text-sm text-muted-foreground md:flex">
            <a href="#modules" className="transition-colors hover:text-foreground">
              Modules
            </a>
            <a href="#platform" className="transition-colors hover:text-foreground">
              Platform
            </a>
            <a href="#verticals" className="transition-colors hover:text-foreground">
              Who we serve
            </a>
          </nav>
          <div className="flex items-center gap-2">
            <Button asChild variant="ghost">
              <Link to="/auth">Sign in</Link>
            </Button>
            <Button asChild className="hidden sm:inline-flex">
              <Link to="/auth">Get started</Link>
            </Button>
          </div>
        </div>
      </header>

      <main>
        {/* Hero */}
        <section className="relative overflow-hidden border-b border-border">
          <div
            aria-hidden="true"
            className="pointer-events-none absolute inset-0 bg-gradient-to-b from-secondary/60 to-background"
          />
          <div className="relative mx-auto max-w-6xl px-6 py-20 md:py-28">
            <p className="mb-5 inline-flex items-center gap-2 rounded-full border border-border bg-card px-3 py-1 text-xs font-medium text-muted-foreground">
              <Sparkles className="h-3 w-3 text-accent" aria-hidden="true" /> AI-powered. IACET-aligned.
              Built by Boost Strategy Group.
            </p>
            <h1 className="max-w-3xl font-display text-5xl font-semibold leading-[1.04] tracking-tight text-balance md:text-6xl">
              Four modules. One platform.
              <br />
              <span className="text-accent">A workforce that performs.</span>
            </h1>
            <p className="mt-6 max-w-2xl text-lg leading-relaxed text-muted-foreground text-pretty">
              Boost!Roles, Boost!Perform, Boost!Pulse, and Boost!Learn — a unified system for role
              design, performance, engagement, and credentialed learning. Self-paced, hybrid, and
              live-instructor-led, all in your brand.
            </p>
            <div className="mt-8 flex flex-wrap items-center gap-3">
              <Button asChild size="lg">
                <Link to="/auth">
                  Get started
                  <ArrowRight className="h-4 w-4" aria-hidden="true" />
                </Link>
              </Button>
              <Button asChild size="lg" variant="outline">
                <a href="#modules">Tour the modules</a>
              </Button>
            </div>
            <dl className="mt-14 grid max-w-2xl grid-cols-2 gap-x-8 gap-y-6 sm:grid-cols-4">
              {[
                { v: "4", l: "Integrated modules" },
                { v: "IACET", l: "Aligned provider" },
                { v: "Multi", l: "Tenant & white-label" },
                { v: "RTI", l: "Apprenticeship-ready" },
              ].map((s) => (
                <div key={s.l}>
                  <dt className="font-display text-2xl font-semibold text-foreground">{s.v}</dt>
                  <dd className="mt-1 text-xs text-muted-foreground">{s.l}</dd>
                </div>
              ))}
            </dl>
          </div>
        </section>

        {/* Modules */}
        <section id="modules" className="bg-card">
          <div className="mx-auto max-w-6xl px-6 py-20">
            <div className="max-w-2xl">
              <h2 className="font-display text-3xl font-semibold tracking-tight md:text-4xl">
                The four modules
              </h2>
              <p className="mt-3 text-muted-foreground text-pretty">
                Use one. Use all four. They share the same employee directory, the same approvals,
                and the same audit trail.
              </p>
            </div>
            <div className="mt-10 grid gap-6 md:grid-cols-2">
              {MODULES.map(({ icon: Icon, name, tag, body, points }) => (
                <div
                  key={name}
                  className="group rounded-xl border border-border bg-background p-6 transition-colors hover:border-accent/60"
                >
                  <div className="flex items-start justify-between gap-4">
                    <div className="grid h-11 w-11 place-items-center rounded-lg bg-accent/15 text-accent">
                      <Icon className="h-5 w-5" aria-hidden="true" />
                    </div>
                    <span className="rounded-full border border-border px-2.5 py-1 text-xs font-medium uppercase tracking-wide text-muted-foreground">
                      {tag}
                    </span>
                  </div>
                  <h3 className="mt-5 font-display text-xl font-semibold">{name}</h3>
                  <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{body}</p>
                  <ul className="mt-4 space-y-2">
                    {points.map((p) => (
                      <li key={p} className="flex items-center gap-2 text-sm text-foreground">
                        <CheckCircle2 className="h-4 w-4 shrink-0 text-accent" aria-hidden="true" />
                        {p}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* How it works */}
        <section className="border-t border-border">
          <div className="mx-auto max-w-6xl px-6 py-20">
            <div className="max-w-2xl">
              <h2 className="font-display text-3xl font-semibold tracking-tight md:text-4xl">
                From setup to credential
              </h2>
              <p className="mt-3 text-muted-foreground text-pretty">
                A guided path from standing up your tenant to issuing verifiable credentials.
              </p>
            </div>
            <ol className="mt-10 grid gap-6 md:grid-cols-3">
              {STEPS.map(({ step, title, body }) => (
                <li key={step} className="rounded-xl border border-border bg-card p-6">
                  <span className="font-display text-3xl font-semibold text-accent">{step}</span>
                  <h3 className="mt-3 font-display text-lg font-semibold">{title}</h3>
                  <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{body}</p>
                </li>
              ))}
            </ol>
          </div>
        </section>

        {/* Platform capabilities */}
        <section id="platform" className="border-t border-border bg-card">
          <div className="mx-auto max-w-6xl px-6 py-20">
            <div className="max-w-2xl">
              <h2 className="font-display text-3xl font-semibold tracking-tight md:text-4xl">
                Built for the way you operate
              </h2>
              <p className="mt-3 text-muted-foreground text-pretty">
                Enterprise-grade controls without the enterprise overhead.
              </p>
            </div>
            <div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              {CAPABILITIES.map(({ icon: Icon, title, body }) => (
                <div key={title} className="rounded-xl border border-border bg-background p-6">
                  <div className="grid h-11 w-11 place-items-center rounded-lg bg-accent/15 text-accent">
                    <Icon className="h-5 w-5" aria-hidden="true" />
                  </div>
                  <h3 className="mt-4 font-display text-lg font-semibold">{title}</h3>
                  <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{body}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Verticals */}
        <section id="verticals" className="border-t border-border">
          <div className="mx-auto max-w-6xl px-6 py-20">
            <div className="max-w-2xl">
              <h2 className="font-display text-3xl font-semibold tracking-tight md:text-4xl">
                Who we serve
              </h2>
              <p className="mt-3 text-muted-foreground text-pretty">
                Programs across these verticals run on BOOST today.
              </p>
            </div>
            <ul className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              {VERTICALS.map((v) => (
                <li
                  key={v}
                  className="flex items-center gap-3 rounded-lg border border-border bg-card px-4 py-3 text-sm"
                >
                  <CheckCircle2 className="h-4 w-4 shrink-0 text-accent" aria-hidden="true" />
                  {v}
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* CTA */}
        <section className="border-t border-border bg-primary text-primary-foreground">
          <div className="mx-auto max-w-6xl px-6 py-20 text-center">
            <h2 className="font-display text-3xl font-semibold tracking-tight text-balance md:text-4xl">
              Ready to see BOOST in your brand?
            </h2>
            <p className="mx-auto mt-3 max-w-xl text-primary-foreground/80 text-pretty">
              Sign in or request a tenant to get started with role design, performance, engagement,
              and credentialed learning.
            </p>
            <div className="mt-8 flex justify-center">
              <Button asChild size="lg" variant="secondary">
                <Link to="/auth">
                  Get started
                  <ArrowRight className="h-4 w-4" aria-hidden="true" />
                </Link>
              </Button>
            </div>
          </div>
        </section>
      </main>

      <footer className="border-t border-border">
        <div className="mx-auto max-w-6xl px-6 py-8 text-sm text-muted-foreground">
          © {new Date().getFullYear()} Boost Strategy Group. IACET accredited provider. ASWB® is a
          registered trademark of the Association of Social Work Boards.
        </div>
      </footer>
    </div>
  );
}
