/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppPracticeRouteImport } from './routes/_app/practice'
import { Route as AppMockRouteImport } from './routes/_app/mock'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppSessionIdRouteImport } from './routes/_app/session.$id'
import { Route as AppAdminStudentsRouteImport } from './routes/_app/admin.students'
import { Route as AppAdminQuestionsRouteImport } from './routes/_app/admin.questions'
import { Route as AppAdminAnalyticsRouteImport } from './routes/_app/admin.analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRoute,
} as any)
const AppMockRoute = AppMockRouteImport.update({
  id: '/mock',
  path: '/mock',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionIdRoute = AppSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStudentsRoute = AppAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminQuestionsRoute = AppAdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/mock': typeof AppMockRoute
  '/practice': typeof AppPracticeRoute
  '/review': typeof AppReviewRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/questions': typeof AppAdminQuestionsRoute
  '/admin/students': typeof AppAdminStudentsRoute
  '/session/$id': typeof AppSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/mock': typeof AppMockRoute
  '/practice': typeof AppPracticeRoute
  '/review': typeof AppReviewRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/questions': typeof AppAdminQuestionsRoute
  '/admin/students': typeof AppAdminStudentsRoute
  '/session/$id': typeof AppSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/mock': typeof AppMockRoute
  '/_app/practice': typeof AppPracticeRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/_app/admin/questions': typeof AppAdminQuestionsRoute
  '/_app/admin/students': typeof AppAdminStudentsRoute
  '/_app/session/$id': typeof AppSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/mock'
    | '/practice'
    | '/review'
    | '/admin/analytics'
    | '/admin/questions'
    | '/admin/students'
    | '/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/mock'
    | '/practice'
    | '/review'
    | '/admin/analytics'
    | '/admin/questions'
    | '/admin/students'
    | '/session/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/mock'
    | '/_app/practice'
    | '/_app/review'
    | '/_app/admin/analytics'
    | '/_app/admin/questions'
    | '/_app/admin/students'
    | '/_app/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice': {
      id: '/_app/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mock': {
      id: '/_app/mock'
      path: '/mock'
      fullPath: '/mock'
      preLoaderRoute: typeof AppMockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/session/$id': {
      id: '/_app/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof AppSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/students': {
      id: '/_app/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AppAdminStudentsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/questions': {
      id: '/_app/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AppAdminQuestionsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/analytics': {
      id: '/_app/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminQuestionsRoute: typeof AppAdminQuestionsRoute
  AppAdminStudentsRoute: typeof AppAdminStudentsRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminQuestionsRoute: AppAdminQuestionsRoute,
  AppAdminStudentsRoute: AppAdminStudentsRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppMockRoute: typeof AppMockRoute
  AppPracticeRoute: typeof AppPracticeRoute
  AppReviewRoute: typeof AppReviewRoute
  AppSessionIdRoute: typeof AppSessionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppMockRoute: AppMockRoute,
  AppPracticeRoute: AppPracticeRoute,
  AppReviewRoute: AppReviewRoute,
  AppSessionIdRoute: AppSessionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
