/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as ApprovalsTokenRouteImport } from './routes/approvals.$token'
import { Route as AppVaultRouteImport } from './routes/_app/vault'
import { Route as AppReviewRouteImport } from './routes/_app/review'
import { Route as AppPracticeRouteImport } from './routes/_app/practice'
import { Route as AppMockRouteImport } from './routes/_app/mock'
import { Route as AppLaunchpadRouteImport } from './routes/_app/launchpad'
import { Route as AppEmployeesRouteImport } from './routes/_app/employees'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCatalogRouteImport } from './routes/_app/catalog'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AppSessionIdRouteImport } from './routes/_app/session.$id'
import { Route as AppModulesRolesRouteImport } from './routes/_app/modules.roles'
import { Route as AppModulesPulseRouteImport } from './routes/_app/modules.pulse'
import { Route as AppModulesPerformRouteImport } from './routes/_app/modules.perform'
import { Route as AppModulesLearnRouteImport } from './routes/_app/modules.learn'
import { Route as AppLearnCourseIdRouteImport } from './routes/_app/learn.$courseId'
import { Route as AppAdminTenantsRouteImport } from './routes/_app/admin.tenants'
import { Route as AppAdminStudentsRouteImport } from './routes/_app/admin.students'
import { Route as AppAdminStudentManagementRouteImport } from './routes/_app/admin.student-management'
import { Route as AppAdminQuestionsRouteImport } from './routes/_app/admin.questions'
import { Route as AppAdminPublicationsRouteImport } from './routes/_app/admin.publications'
import { Route as AppAdminIntegrationsRouteImport } from './routes/_app/admin.integrations'
import { Route as AppAdminCoursesRouteImport } from './routes/_app/admin.courses'
import { Route as AppAdminAnalyticsRouteImport } from './routes/_app/admin.analytics'
import { Route as AppAdminAiFactoryRouteImport } from './routes/_app/admin.ai-factory'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AppAdminTenantsTenantIdRouteImport } from './routes/_app/admin.tenants.$tenantId'
import { Route as AppAdminCoursesCourseIdRouteImport } from './routes/_app/admin.courses.$courseId'
import { Route as AppAdminCoursesCourseIdNeedsAssessmentRouteImport } from './routes/_app/admin.courses.$courseId.needs-assessment'
import { Route as AppAdminCoursesCourseIdAssessmentsAssessmentIdRouteImport } from './routes/_app/admin.courses.$courseId.assessments.$assessmentId'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsTokenRoute = ApprovalsTokenRouteImport.update({
  id: '/approvals/$token',
  path: '/approvals/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRoute,
} as any)
const AppMockRoute = AppMockRouteImport.update({
  id: '/mock',
  path: '/mock',
  getParentRoute: () => AppRoute,
} as any)
const AppLaunchpadRoute = AppLaunchpadRouteImport.update({
  id: '/launchpad',
  path: '/launchpad',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSessionIdRoute = AppSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesRolesRoute = AppModulesRolesRouteImport.update({
  id: '/modules/roles',
  path: '/modules/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesPulseRoute = AppModulesPulseRouteImport.update({
  id: '/modules/pulse',
  path: '/modules/pulse',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesPerformRoute = AppModulesPerformRouteImport.update({
  id: '/modules/perform',
  path: '/modules/perform',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesLearnRoute = AppModulesLearnRouteImport.update({
  id: '/modules/learn',
  path: '/modules/learn',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnCourseIdRoute = AppLearnCourseIdRouteImport.update({
  id: '/learn/$courseId',
  path: '/learn/$courseId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTenantsRoute = AppAdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminStudentsRoute = AppAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminStudentManagementRoute =
  AppAdminStudentManagementRouteImport.update({
    id: '/student-management',
    path: '/student-management',
    getParentRoute: () => AppAdminRoute,
  } as any)
const AppAdminQuestionsRoute = AppAdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPublicationsRoute = AppAdminPublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminIntegrationsRoute = AppAdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCoursesRoute = AppAdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAiFactoryRoute = AppAdminAiFactoryRouteImport.update({
  id: '/ai-factory',
  path: '/ai-factory',
  getParentRoute: () => AppAdminRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAdminTenantsTenantIdRoute = AppAdminTenantsTenantIdRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => AppAdminTenantsRoute,
} as any)
const AppAdminCoursesCourseIdRoute = AppAdminCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AppAdminCoursesRoute,
} as any)
const AppAdminCoursesCourseIdNeedsAssessmentRoute =
  AppAdminCoursesCourseIdNeedsAssessmentRouteImport.update({
    id: '/needs-assessment',
    path: '/needs-assessment',
    getParentRoute: () => AppAdminCoursesCourseIdRoute,
  } as any)
const AppAdminCoursesCourseIdAssessmentsAssessmentIdRoute =
  AppAdminCoursesCourseIdAssessmentsAssessmentIdRouteImport.update({
    id: '/assessments/$assessmentId',
    path: '/assessments/$assessmentId',
    getParentRoute: () => AppAdminCoursesCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/catalog': typeof AppCatalogRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRoute
  '/launchpad': typeof AppLaunchpadRoute
  '/mock': typeof AppMockRoute
  '/practice': typeof AppPracticeRoute
  '/review': typeof AppReviewRoute
  '/vault': typeof AppVaultRoute
  '/approvals/$token': typeof ApprovalsTokenRoute
  '/c/$slug': typeof CSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/ai-factory': typeof AppAdminAiFactoryRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/courses': typeof AppAdminCoursesRouteWithChildren
  '/admin/integrations': typeof AppAdminIntegrationsRoute
  '/admin/publications': typeof AppAdminPublicationsRoute
  '/admin/questions': typeof AppAdminQuestionsRoute
  '/admin/student-management': typeof AppAdminStudentManagementRoute
  '/admin/students': typeof AppAdminStudentsRoute
  '/admin/tenants': typeof AppAdminTenantsRouteWithChildren
  '/learn/$courseId': typeof AppLearnCourseIdRoute
  '/modules/learn': typeof AppModulesLearnRoute
  '/modules/perform': typeof AppModulesPerformRoute
  '/modules/pulse': typeof AppModulesPulseRoute
  '/modules/roles': typeof AppModulesRolesRoute
  '/session/$id': typeof AppSessionIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/courses/$courseId': typeof AppAdminCoursesCourseIdRouteWithChildren
  '/admin/tenants/$tenantId': typeof AppAdminTenantsTenantIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/courses/$courseId/needs-assessment': typeof AppAdminCoursesCourseIdNeedsAssessmentRoute
  '/admin/courses/$courseId/assessments/$assessmentId': typeof AppAdminCoursesCourseIdAssessmentsAssessmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/catalog': typeof AppCatalogRoute
  '/dashboard': typeof AppDashboardRoute
  '/employees': typeof AppEmployeesRoute
  '/launchpad': typeof AppLaunchpadRoute
  '/mock': typeof AppMockRoute
  '/practice': typeof AppPracticeRoute
  '/review': typeof AppReviewRoute
  '/vault': typeof AppVaultRoute
  '/approvals/$token': typeof ApprovalsTokenRoute
  '/c/$slug': typeof CSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/ai-factory': typeof AppAdminAiFactoryRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/courses': typeof AppAdminCoursesRouteWithChildren
  '/admin/integrations': typeof AppAdminIntegrationsRoute
  '/admin/publications': typeof AppAdminPublicationsRoute
  '/admin/questions': typeof AppAdminQuestionsRoute
  '/admin/student-management': typeof AppAdminStudentManagementRoute
  '/admin/students': typeof AppAdminStudentsRoute
  '/admin/tenants': typeof AppAdminTenantsRouteWithChildren
  '/learn/$courseId': typeof AppLearnCourseIdRoute
  '/modules/learn': typeof AppModulesLearnRoute
  '/modules/perform': typeof AppModulesPerformRoute
  '/modules/pulse': typeof AppModulesPulseRoute
  '/modules/roles': typeof AppModulesRolesRoute
  '/session/$id': typeof AppSessionIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/courses/$courseId': typeof AppAdminCoursesCourseIdRouteWithChildren
  '/admin/tenants/$tenantId': typeof AppAdminTenantsTenantIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/courses/$courseId/needs-assessment': typeof AppAdminCoursesCourseIdNeedsAssessmentRoute
  '/admin/courses/$courseId/assessments/$assessmentId': typeof AppAdminCoursesCourseIdAssessmentsAssessmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/catalog': typeof AppCatalogRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/employees': typeof AppEmployeesRoute
  '/_app/launchpad': typeof AppLaunchpadRoute
  '/_app/mock': typeof AppMockRoute
  '/_app/practice': typeof AppPracticeRoute
  '/_app/review': typeof AppReviewRoute
  '/_app/vault': typeof AppVaultRoute
  '/approvals/$token': typeof ApprovalsTokenRoute
  '/c/$slug': typeof CSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_app/admin/ai-factory': typeof AppAdminAiFactoryRoute
  '/_app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/_app/admin/courses': typeof AppAdminCoursesRouteWithChildren
  '/_app/admin/integrations': typeof AppAdminIntegrationsRoute
  '/_app/admin/publications': typeof AppAdminPublicationsRoute
  '/_app/admin/questions': typeof AppAdminQuestionsRoute
  '/_app/admin/student-management': typeof AppAdminStudentManagementRoute
  '/_app/admin/students': typeof AppAdminStudentsRoute
  '/_app/admin/tenants': typeof AppAdminTenantsRouteWithChildren
  '/_app/learn/$courseId': typeof AppLearnCourseIdRoute
  '/_app/modules/learn': typeof AppModulesLearnRoute
  '/_app/modules/perform': typeof AppModulesPerformRoute
  '/_app/modules/pulse': typeof AppModulesPulseRoute
  '/_app/modules/roles': typeof AppModulesRolesRoute
  '/_app/session/$id': typeof AppSessionIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_app/admin/courses/$courseId': typeof AppAdminCoursesCourseIdRouteWithChildren
  '/_app/admin/tenants/$tenantId': typeof AppAdminTenantsTenantIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_app/admin/courses/$courseId/needs-assessment': typeof AppAdminCoursesCourseIdNeedsAssessmentRoute
  '/_app/admin/courses/$courseId/assessments/$assessmentId': typeof AppAdminCoursesCourseIdAssessmentsAssessmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/unsubscribe'
    | '/admin'
    | '/catalog'
    | '/dashboard'
    | '/employees'
    | '/launchpad'
    | '/mock'
    | '/practice'
    | '/review'
    | '/vault'
    | '/approvals/$token'
    | '/c/$slug'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/admin/ai-factory'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/integrations'
    | '/admin/publications'
    | '/admin/questions'
    | '/admin/student-management'
    | '/admin/students'
    | '/admin/tenants'
    | '/learn/$courseId'
    | '/modules/learn'
    | '/modules/perform'
    | '/modules/pulse'
    | '/modules/roles'
    | '/session/$id'
    | '/lovable/email/suppression'
    | '/admin/courses/$courseId'
    | '/admin/tenants/$tenantId'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/courses/$courseId/needs-assessment'
    | '/admin/courses/$courseId/assessments/$assessmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/unsubscribe'
    | '/admin'
    | '/catalog'
    | '/dashboard'
    | '/employees'
    | '/launchpad'
    | '/mock'
    | '/practice'
    | '/review'
    | '/vault'
    | '/approvals/$token'
    | '/c/$slug'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/admin/ai-factory'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/integrations'
    | '/admin/publications'
    | '/admin/questions'
    | '/admin/student-management'
    | '/admin/students'
    | '/admin/tenants'
    | '/learn/$courseId'
    | '/modules/learn'
    | '/modules/perform'
    | '/modules/pulse'
    | '/modules/roles'
    | '/session/$id'
    | '/lovable/email/suppression'
    | '/admin/courses/$courseId'
    | '/admin/tenants/$tenantId'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/courses/$courseId/needs-assessment'
    | '/admin/courses/$courseId/assessments/$assessmentId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/unsubscribe'
    | '/_app/admin'
    | '/_app/catalog'
    | '/_app/dashboard'
    | '/_app/employees'
    | '/_app/launchpad'
    | '/_app/mock'
    | '/_app/practice'
    | '/_app/review'
    | '/_app/vault'
    | '/approvals/$token'
    | '/c/$slug'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/_app/admin/ai-factory'
    | '/_app/admin/analytics'
    | '/_app/admin/courses'
    | '/_app/admin/integrations'
    | '/_app/admin/publications'
    | '/_app/admin/questions'
    | '/_app/admin/student-management'
    | '/_app/admin/students'
    | '/_app/admin/tenants'
    | '/_app/learn/$courseId'
    | '/_app/modules/learn'
    | '/_app/modules/perform'
    | '/_app/modules/pulse'
    | '/_app/modules/roles'
    | '/_app/session/$id'
    | '/lovable/email/suppression'
    | '/_app/admin/courses/$courseId'
    | '/_app/admin/tenants/$tenantId'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_app/admin/courses/$courseId/needs-assessment'
    | '/_app/admin/courses/$courseId/assessments/$assessmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApprovalsTokenRoute: typeof ApprovalsTokenRoute
  CSlugRoute: typeof CSlugRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals/$token': {
      id: '/approvals/$token'
      path: '/approvals/$token'
      fullPath: '/approvals/$token'
      preLoaderRoute: typeof ApprovalsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vault': {
      id: '/_app/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/review': {
      id: '/_app/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice': {
      id: '/_app/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mock': {
      id: '/_app/mock'
      path: '/mock'
      fullPath: '/mock'
      preLoaderRoute: typeof AppMockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/launchpad': {
      id: '/_app/launchpad'
      path: '/launchpad'
      fullPath: '/launchpad'
      preLoaderRoute: typeof AppLaunchpadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees': {
      id: '/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog': {
      id: '/_app/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/session/$id': {
      id: '/_app/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof AppSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modules/roles': {
      id: '/_app/modules/roles'
      path: '/modules/roles'
      fullPath: '/modules/roles'
      preLoaderRoute: typeof AppModulesRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modules/pulse': {
      id: '/_app/modules/pulse'
      path: '/modules/pulse'
      fullPath: '/modules/pulse'
      preLoaderRoute: typeof AppModulesPulseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modules/perform': {
      id: '/_app/modules/perform'
      path: '/modules/perform'
      fullPath: '/modules/perform'
      preLoaderRoute: typeof AppModulesPerformRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modules/learn': {
      id: '/_app/modules/learn'
      path: '/modules/learn'
      fullPath: '/modules/learn'
      preLoaderRoute: typeof AppModulesLearnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/learn/$courseId': {
      id: '/_app/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof AppLearnCourseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tenants': {
      id: '/_app/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AppAdminTenantsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/students': {
      id: '/_app/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AppAdminStudentsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/student-management': {
      id: '/_app/admin/student-management'
      path: '/student-management'
      fullPath: '/admin/student-management'
      preLoaderRoute: typeof AppAdminStudentManagementRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/questions': {
      id: '/_app/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AppAdminQuestionsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/publications': {
      id: '/_app/admin/publications'
      path: '/publications'
      fullPath: '/admin/publications'
      preLoaderRoute: typeof AppAdminPublicationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/integrations': {
      id: '/_app/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AppAdminIntegrationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/courses': {
      id: '/_app/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AppAdminCoursesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/analytics': {
      id: '/_app/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/ai-factory': {
      id: '/_app/admin/ai-factory'
      path: '/ai-factory'
      fullPath: '/admin/ai-factory'
      preLoaderRoute: typeof AppAdminAiFactoryRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/tenants/$tenantId': {
      id: '/_app/admin/tenants/$tenantId'
      path: '/$tenantId'
      fullPath: '/admin/tenants/$tenantId'
      preLoaderRoute: typeof AppAdminTenantsTenantIdRouteImport
      parentRoute: typeof AppAdminTenantsRoute
    }
    '/_app/admin/courses/$courseId': {
      id: '/_app/admin/courses/$courseId'
      path: '/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AppAdminCoursesCourseIdRouteImport
      parentRoute: typeof AppAdminCoursesRoute
    }
    '/_app/admin/courses/$courseId/needs-assessment': {
      id: '/_app/admin/courses/$courseId/needs-assessment'
      path: '/needs-assessment'
      fullPath: '/admin/courses/$courseId/needs-assessment'
      preLoaderRoute: typeof AppAdminCoursesCourseIdNeedsAssessmentRouteImport
      parentRoute: typeof AppAdminCoursesCourseIdRoute
    }
    '/_app/admin/courses/$courseId/assessments/$assessmentId': {
      id: '/_app/admin/courses/$courseId/assessments/$assessmentId'
      path: '/assessments/$assessmentId'
      fullPath: '/admin/courses/$courseId/assessments/$assessmentId'
      preLoaderRoute: typeof AppAdminCoursesCourseIdAssessmentsAssessmentIdRouteImport
      parentRoute: typeof AppAdminCoursesCourseIdRoute
    }
  }
}

interface AppAdminCoursesCourseIdRouteChildren {
  AppAdminCoursesCourseIdNeedsAssessmentRoute: typeof AppAdminCoursesCourseIdNeedsAssessmentRoute
  AppAdminCoursesCourseIdAssessmentsAssessmentIdRoute: typeof AppAdminCoursesCourseIdAssessmentsAssessmentIdRoute
}

const AppAdminCoursesCourseIdRouteChildren: AppAdminCoursesCourseIdRouteChildren =
  {
    AppAdminCoursesCourseIdNeedsAssessmentRoute:
      AppAdminCoursesCourseIdNeedsAssessmentRoute,
    AppAdminCoursesCourseIdAssessmentsAssessmentIdRoute:
      AppAdminCoursesCourseIdAssessmentsAssessmentIdRoute,
  }

const AppAdminCoursesCourseIdRouteWithChildren =
  AppAdminCoursesCourseIdRoute._addFileChildren(
    AppAdminCoursesCourseIdRouteChildren,
  )

interface AppAdminCoursesRouteChildren {
  AppAdminCoursesCourseIdRoute: typeof AppAdminCoursesCourseIdRouteWithChildren
}

const AppAdminCoursesRouteChildren: AppAdminCoursesRouteChildren = {
  AppAdminCoursesCourseIdRoute: AppAdminCoursesCourseIdRouteWithChildren,
}

const AppAdminCoursesRouteWithChildren = AppAdminCoursesRoute._addFileChildren(
  AppAdminCoursesRouteChildren,
)

interface AppAdminTenantsRouteChildren {
  AppAdminTenantsTenantIdRoute: typeof AppAdminTenantsTenantIdRoute
}

const AppAdminTenantsRouteChildren: AppAdminTenantsRouteChildren = {
  AppAdminTenantsTenantIdRoute: AppAdminTenantsTenantIdRoute,
}

const AppAdminTenantsRouteWithChildren = AppAdminTenantsRoute._addFileChildren(
  AppAdminTenantsRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminAiFactoryRoute: typeof AppAdminAiFactoryRoute
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminCoursesRoute: typeof AppAdminCoursesRouteWithChildren
  AppAdminIntegrationsRoute: typeof AppAdminIntegrationsRoute
  AppAdminPublicationsRoute: typeof AppAdminPublicationsRoute
  AppAdminQuestionsRoute: typeof AppAdminQuestionsRoute
  AppAdminStudentManagementRoute: typeof AppAdminStudentManagementRoute
  AppAdminStudentsRoute: typeof AppAdminStudentsRoute
  AppAdminTenantsRoute: typeof AppAdminTenantsRouteWithChildren
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAiFactoryRoute: AppAdminAiFactoryRoute,
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminCoursesRoute: AppAdminCoursesRouteWithChildren,
  AppAdminIntegrationsRoute: AppAdminIntegrationsRoute,
  AppAdminPublicationsRoute: AppAdminPublicationsRoute,
  AppAdminQuestionsRoute: AppAdminQuestionsRoute,
  AppAdminStudentManagementRoute: AppAdminStudentManagementRoute,
  AppAdminStudentsRoute: AppAdminStudentsRoute,
  AppAdminTenantsRoute: AppAdminTenantsRouteWithChildren,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCatalogRoute: typeof AppCatalogRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppLaunchpadRoute: typeof AppLaunchpadRoute
  AppMockRoute: typeof AppMockRoute
  AppPracticeRoute: typeof AppPracticeRoute
  AppReviewRoute: typeof AppReviewRoute
  AppVaultRoute: typeof AppVaultRoute
  AppLearnCourseIdRoute: typeof AppLearnCourseIdRoute
  AppModulesLearnRoute: typeof AppModulesLearnRoute
  AppModulesPerformRoute: typeof AppModulesPerformRoute
  AppModulesPulseRoute: typeof AppModulesPulseRoute
  AppModulesRolesRoute: typeof AppModulesRolesRoute
  AppSessionIdRoute: typeof AppSessionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCatalogRoute: AppCatalogRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppLaunchpadRoute: AppLaunchpadRoute,
  AppMockRoute: AppMockRoute,
  AppPracticeRoute: AppPracticeRoute,
  AppReviewRoute: AppReviewRoute,
  AppVaultRoute: AppVaultRoute,
  AppLearnCourseIdRoute: AppLearnCourseIdRoute,
  AppModulesLearnRoute: AppModulesLearnRoute,
  AppModulesPerformRoute: AppModulesPerformRoute,
  AppModulesPulseRoute: AppModulesPulseRoute,
  AppModulesRolesRoute: AppModulesRolesRoute,
  AppSessionIdRoute: AppSessionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApprovalsTokenRoute: ApprovalsTokenRoute,
  CSlugRoute: CSlugRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
